#!/bin/sh
#========================================
#   Linux Distribution: Manjaro/Debian 8+/
#   Author: 6donote4 <mailto:do_note@hotmail.com>
#   Dscription: alias for docker cp 
#   Version: 0.0.1
#   Blog: https://www.donote.tk https://6donote4.github.io
#========================================
 
docker cp $1 $2
exit 0
